title:            Lichens of New York City
url:              http://lichens.nyc
baseurl:          ""
email:            patch@cpan.org
twitter_username: nickpatch
github_username:  nyclichens
encoding:         utf-8
markdown:         kramdown
timezone:         America/New_York
