title:            Lichens of New York City
description:      'Lichen checklists for New York City: The Bronx, Brooklyn, Manhattan, Queens, and Staten Island.'
url:              http://lichens.nyc
baseurl:          ''
email:            patch@cpan.org
twitter_username: novapatch
github_username:  nyclichens
encoding:         utf-8
markdown:         kramdown
timezone:         America/New_York
